### ISSUE TITLE
NavSec2 - Navigation Section 2

### ISSUE THREAD

**Issue by HTitcomb-Day** [pro-fas/lagergeld#18]
## Navigation Section 2

![navsec2](https://user-images.githubusercontent.com/30464879/29188151-1b8e70ce-7e0a-11e7-9483-14ef193317f2.png)

## Composes

- [x] **Col4** - Column 4 (Lager Sylt virtual tour) #19 
- [x] **Col5** - Column 5 (Lager Sylt 3D reconstruction) #20 
- [x] **Completed**

**Comment by bannerintheUK** [comment]
Done
