### ISSUE TITLE
Col4 - Column4 (Lager Sylt virtual tour)

### ISSUE THREAD

**Issue by HTitcomb-Day** [pro-fas/lagergeld#19]
## Column 4 (Lager Sylt virtual tour)

![col4](https://user-images.githubusercontent.com/30464879/29188721-f3346a32-7e0b-11e7-845e-e144aac3f29e.png)

## Composes

+ **Col1txt**
Caption1: ''Lager Sylt
Caption 2: **virtual tour**"

### Text Properties

+ **Caption1:**
Font Family: Roboto
Font Style: Regular
Font Size: 48px
Line Height: 42px
Align: Center
Fill: Solid
#FFFFFF

+ **Caption2:**
Font Family: Roboto
Font Style: Bold
Font Size: 58px
Line Height: 42px
Align: Center
Fill: Solid
#FFFFFF

+ **Background Image**
![virtual tour image](https://user-images.githubusercontent.com/30464879/29189793-bf0967d6-7e0f-11e7-8482-062708dd478e.png)

**Comment by bannerintheUK** [comment]
Done
