### ISSUE TITLE
Col5 - Column 5 (Lager Sylt 3D Reconstruction)

### ISSUE THREAD

**Issue by HTitcomb-Day** [pro-fas/lagergeld#20]
## Column 5 (Lager Sylt 3D Reconstruction)

![col5](https://user-images.githubusercontent.com/30464879/29189865-fa2fc436-7e0f-11e7-803a-e789c3b5cf27.png)

## Composes

+ **Col5txt:**
Caption 1: "Lager Sylt
Caption 2: **3D reconstruction**"

### Text Properties

+ **Caption 1:**
Font Family: Roboto
Font Style: Regular
Font Size: 48px
Line Height: 42px
Align: Center
Fill: Solid
#2E414E

+ **Caption 2:**
Font Family: Roboto
Font Style: Bold
Font Size: 58px
Line Height: 42px
Align: Center
Fill: Solid
#2E414E

+ **Background Image**

![3d reconstruction image](https://user-images.githubusercontent.com/30464879/29190140-e8ff815a-7e10-11e7-99f4-00002a38bef9.png)

**Comment by bannerintheUK** [comment]
Done
