### ISSUE TITLE
RefSec - References Section

### ISSUE THREAD

**Issue by HTitcomb-Day** [pro-fas/lagergeld#21]
## References Section

![refsec 2](https://user-images.githubusercontent.com/30464879/29190240-410f7576-7e11-11e7-8212-ae5f335aaf54.png)

## Composes

+ Caption: "sources and references"

+ Background
Transparent
Stroke: Solid
Align: Inside
Width: 4px
#304050

+ Text
Font Family: Roboto
Font Style: Regular
Font Size: 36px
Line Height: 42px
Align: Center
Fill: Solid
#2E414E

- [x] **Completed**

**Comment by bannerintheUK** [comment]
Done
