### ISSUE TITLE
Foo1 - Footer

### ISSUE THREAD

**Issue by HTitcomb-Day** [pro-fas/lagergeld#22]
## Footer

![foo1 1](https://user-images.githubusercontent.com/30464879/29190510-5517fb82-7e12-11e7-9697-5c98daa0d6bd.png)

## Composes

+ Background - Transparent

+ Line
Stroke: Solid
Align: Center
Width: 2px
#828282

+ Image 1 (centre of archaeology)

![archaeology icon](https://user-images.githubusercontent.com/30464879/29190633-d2b1f89a-7e12-11e7-865d-7ef79b2428bc.png)

+ Image 2 (Staffs Uni)

![staffs icon](https://user-images.githubusercontent.com/30464879/29190644-da95b3ee-7e12-11e7-8d8e-45b2e4e6a528.png)

**Comment by bannerintheUK** [comment]
Done
